services:
  mydb:
    image: postgres:16
    container_name: mydb
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_panel
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mydb
    networks:
      - app-network
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    ports:
      - "8080:8080"
    depends_on:
      - mydb
      - redis
    networks:
      - app-network
    env_file:
      - .env
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
